//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpowiedz
    {
        public int IdOdpowiedzi { get; set; }
        public int IdPytanie { get; set; }
        public string Tekst { get; set; }
    
        public virtual Pytanie Pytania { get; set; }
    }
}
